### registering a drone;
PUT http://localhost:8080/drone
Content-Type: application/json

{
  "serialNumber": "D06",
  "model": "Lightweight",
  "weightLimit": 15
}

### loading a drone with medication items;


### checking loaded medication items for a given drone;


### checking available drones for loading;
GET http://localhost:8080/drones/available

### check drone battery level for a given drone;
GET http://localhost:8080/drone/D00/battery